// ════════════════════════════════════════════════════════════════════════════
// PRINT SHEET PRESETS
// Grids and roll sizes from major paper & label manufacturers:
//  - ISO 216 paper (A4 210×297, A5 148×210) and US Letter (215.9×279.4)
//  - Avery / Zweckform / Herma multi-purpose A4 label matrices
//  - Avery US Letter label sheets (5160 / 5163 / 5164 / 5260)
//  - Thermal-label roll sizes (Zebra, Rollo, MUNBYN, Brother, DYMO)
//  - Continuous receipt / fanfold roll widths
// ════════════════════════════════════════════════════════════════════════════

export interface SheetPreset {
    id: string;
    name: string;
    paperSize: 'A4' | 'Letter' | 'Roll' | 'Custom';
    paperWidthMm: number;
    paperHeightMm: number;
    cols: number;
    rows: number;
    labelWidthMm: number;
    labelHeightMm: number;
    marginTopMm: number;
    marginBottomMm: number;
    marginLeftMm: number;
    marginRightMm: number;
    gapXMm: number;
    gapYMm: number;
    description: string;
}

export const SHEET_PRESETS: SheetPreset[] = [
    {
        id: 'a4-10up',
        name: 'A4 — 95 × 55 mm Badge (10/sheet · 2 × 5)',
        paperSize: 'A4',
        paperWidthMm: 210,
        paperHeightMm: 297,
        cols: 2,
        rows: 5,
        labelWidthMm: 95,
        labelHeightMm: 55,
        marginTopMm: 11,
        marginBottomMm: 11,
        marginLeftMm: 10,
        marginRightMm: 10,
        gapXMm: 0,
        gapYMm: 0,
        description: 'Standard event & employee badge card sheets (95 × 55 mm, 10/sheet).'
    },
    {
        id: 'a4-8up',
        name: 'A4 — 100 × 65 mm Tag (8/sheet · 2 × 4)',
        paperSize: 'A4',
        paperWidthMm: 210,
        paperHeightMm: 297,
        cols: 2,
        rows: 4,
        labelWidthMm: 100,
        labelHeightMm: 65,
        marginTopMm: 18.5,
        marginBottomMm: 18.5,
        marginLeftMm: 5,
        marginRightMm: 5,
        gapXMm: 0,
        gapYMm: 0,
        description: 'Large inventory bin and shelf tags (100 × 65 mm, 8/sheet).'
    },

    // ── A4 multi-purpose sticker sheets ────────────────────────────────────────
    {
        id: 'a4-24up',
        name: 'A4 — 70 × 37 mm (24/sheet · 3 × 8)',
        paperSize: 'A4',
        paperWidthMm: 210,
        paperHeightMm: 297,
        cols: 3,
        rows: 8,
        labelWidthMm: 70,
        labelHeightMm: 37.12,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: 'Standard European A4 sticker sheets (70 × 37 mm, 24/sheet).'
    },
    {
        id: 'a4-65x38',
        name: 'A4 — 65 × 38 mm (21/sheet · 3 × 7)',
        paperSize: 'A4',
        paperWidthMm: 210,
        paperHeightMm: 297,
        cols: 3,
        rows: 7,
        labelWidthMm: 65,
        labelHeightMm: 38,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: 'Herma / Avery A4 65 × 38 mm labels, 21 per sheet.'
    },
    {
        id: 'a4-100x70',
        name: 'A4 — 100 × 70 mm (8/sheet · 2 × 4)',
        paperSize: 'A4',
        paperWidthMm: 210,
        paperHeightMm: 297,
        cols: 2,
        rows: 4,
        labelWidthMm: 100,
        labelHeightMm: 70,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: 'Large A4 box & carton labels (100 × 70 mm, 8/sheet) — Herma 4890 style.'
    },
    {
        id: 'a4-105x74',
        name: 'A4 — 105 × 74 mm (8/sheet · 2 × 4)',
        paperSize: 'A4',
        paperWidthMm: 210,
        paperHeightMm: 297,
        cols: 2,
        rows: 4,
        labelWidthMm: 105,
        labelHeightMm: 74,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: 'European A4 shipping/large label (105 × 74 mm, 8/sheet).'
    },
    {
        id: 'a4-52x42',
        name: 'A4 — 52 × 42 mm (28/sheet · 4 × 7)',
        paperSize: 'A4',
        paperWidthMm: 210,
        paperHeightMm: 297,
        cols: 4,
        rows: 7,
        labelWidthMm: 52,
        labelHeightMm: 42,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: 'High-density A4 label sheet for small barcodes (52 × 42 mm, 28/sheet).'
    },
    {
        id: 'a4-62x42',
        name: 'A4 — 62 × 42 mm (21/sheet · 3 × 7)',
        paperSize: 'A4',
        paperWidthMm: 210,
        paperHeightMm: 297,
        cols: 3,
        rows: 7,
        labelWidthMm: 62,
        labelHeightMm: 42,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: 'A4 62 × 42 mm labels, 21 per sheet (small component / retail).'
    },
    {
        id: 'a4-88x37',
        name: 'A4 — 88 × 37 mm (16/sheet · 2 × 8)',
        paperSize: 'A4',
        paperWidthMm: 210,
        paperHeightMm: 297,
        cols: 2,
        rows: 8,
        labelWidthMm: 88,
        labelHeightMm: 37,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: 'Wide A4 shelf / price labels (88 × 37 mm, 16/sheet).'
    },
    {
        id: 'a4-105x37',
        name: 'A4 — 105 × 37 mm (16/sheet · 2 × 8)',
        paperSize: 'A4',
        paperWidthMm: 210,
        paperHeightMm: 297,
        cols: 2,
        rows: 8,
        labelWidthMm: 105,
        labelHeightMm: 37,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: 'A4 wide strip labels (105 × 37 mm, 16/sheet).'
    },
    {
        id: 'a4-148x100',
        name: 'A4 — 148 × 100 mm (2/sheet · 1 × 2)',
        paperSize: 'A4',
        paperWidthMm: 210,
        paperHeightMm: 297,
        cols: 1,
        rows: 2,
        labelWidthMm: 148,
        labelHeightMm: 100,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: 'A4 half-page labels (148 × 100 mm, 2/sheet).'
    },
    {
        id: 'a4-199x143',
        name: 'A4 — 199 × 143 mm (2/sheet · 1 × 2)',
        paperSize: 'A4',
        paperWidthMm: 210,
        paperHeightMm: 297,
        cols: 1,
        rows: 2,
        labelWidthMm: 199,
        labelHeightMm: 143,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: 'A4 address/folder label (199 × 143 mm, 2/sheet).'
    },

    // ── US Letter label sheets (Avery) ─────────────────────────────────────────
    {
        id: 'avery-5160',
        name: 'Avery 5160 / 8160 (3 × 10 = 30 Labels)',
        paperSize: 'Letter',
        paperWidthMm: 215.9,
        paperHeightMm: 279.4,
        cols: 3,
        rows: 10,
        labelWidthMm: 66.7,
        labelHeightMm: 25.4,
        marginTopMm: 12.7,
        marginBottomMm: 12.7,
        marginLeftMm: 4.8,
        marginRightMm: 4.8,
        gapXMm: 3.1,
        gapYMm: 0,
        description: 'Standard US Letter address labels (1" × 2-5/8", 30/sheet).'
    },
    {
        id: 'avery-5163',
        name: 'Avery 5163 / 8163 (2 × 5 = 10 Shipping Labels)',
        paperSize: 'Letter',
        paperWidthMm: 215.9,
        paperHeightMm: 279.4,
        cols: 2,
        rows: 5,
        labelWidthMm: 101.6,
        labelHeightMm: 50.8,
        marginTopMm: 12.7,
        marginBottomMm: 12.7,
        marginLeftMm: 4.8,
        marginRightMm: 4.8,
        gapXMm: 3.8,
        gapYMm: 0,
        description: 'US Letter parcel and package shipping labels (2" × 4", 10/sheet).'
    },
    {
        id: 'avery-5164',
        name: 'Avery 5164 / 8164 (2 × 4 = 8 Large Labels)',
        paperSize: 'Letter',
        paperWidthMm: 215.9,
        paperHeightMm: 279.4,
        cols: 2,
        rows: 4,
        labelWidthMm: 101.6,
        labelHeightMm: 66.7,
        marginTopMm: 12.7,
        marginBottomMm: 12.7,
        marginLeftMm: 4.8,
        marginRightMm: 4.8,
        gapXMm: 3.8,
        gapYMm: 0,
        description: 'US Letter large shipping labels (3.5" × 5", 8/sheet) — Avery 5164.'
    },
    {
        id: 'avery-5260',
        name: 'Avery 5260 (3 × 10 = 30 Return Labels)',
        paperSize: 'Letter',
        paperWidthMm: 215.9,
        paperHeightMm: 279.4,
        cols: 3,
        rows: 10,
        labelWidthMm: 63.5,
        labelHeightMm: 24.3,
        marginTopMm: 10.1,
        marginBottomMm: 10.1,
        marginLeftMm: 6.4,
        marginRightMm: 6.4,
        gapXMm: 2.5,
        gapYMm: 0,
        description: 'US Letter small return-address labels (1" × 2", 30/sheet) — Avery 5260.'
    },

    // ── Thermal label rolls (desktop / industrial) ─────────────────────────────
    {
        id: 'thermal-4x6',
        name: 'Thermal Roll — 4" × 6" (1-Up Shipping)',
        paperSize: 'Roll',
        paperWidthMm: 101.6,
        paperHeightMm: 152.4,
        cols: 1,
        rows: 1,
        labelWidthMm: 101.6,
        labelHeightMm: 152.4,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: '4 × 6 in direct-thermal shipping roll — Zebra, Rollo, MUNBYN, DYMO 4XL.'
    },
    {
        id: 'thermal-4x4',
        name: 'Thermal Roll — 4" × 4" (Parcel)',
        paperSize: 'Roll',
        paperWidthMm: 101.6,
        paperHeightMm: 101.6,
        cols: 1,
        rows: 1,
        labelWidthMm: 101.6,
        labelHeightMm: 101.6,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: '4 × 4 in square thermal label for e-commerce parcels.'
    },
    {
        id: 'thermal-4x3',
        name: 'Thermal Roll — 4" × 3" (Small Parcel)',
        paperSize: 'Roll',
        paperWidthMm: 101.6,
        paperHeightMm: 76.2,
        cols: 1,
        rows: 1,
        labelWidthMm: 101.6,
        labelHeightMm: 76.2,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: '4 × 3 in thermal label (Zebra / Rollo) for smaller parcels.'
    },
    {
        id: 'thermal-4x2',
        name: 'Thermal Roll — 4" × 2" (Barcode)',
        paperSize: 'Roll',
        paperWidthMm: 101.6,
        paperHeightMm: 50.8,
        cols: 1,
        rows: 1,
        labelWidthMm: 101.6,
        labelHeightMm: 50.8,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: '4 × 2 in thermal warehouse & inventory label.'
    },
    {
        id: 'thermal-6x4',
        name: 'Thermal Roll — 6" × 4" (Carton)',
        paperSize: 'Roll',
        paperWidthMm: 152.4,
        paperHeightMm: 101.6,
        cols: 1,
        rows: 1,
        labelWidthMm: 152.4,
        labelHeightMm: 101.6,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: '6 × 4 in industrial carton label (Zebra industrial, up to 8" width).'
    },
    {
        id: 'thermal-3x2',
        name: 'Thermal Roll — 3" × 2" (Bin / SKU)',
        paperSize: 'Roll',
        paperWidthMm: 76.2,
        paperHeightMm: 50.8,
        cols: 1,
        rows: 1,
        labelWidthMm: 76.2,
        labelHeightMm: 50.8,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: '3 × 2 in thermal bin & SKU label (Zebra, Rollo, MUNBYN).'
    },
    {
        id: 'thermal-3x3',
        name: 'Thermal Roll — 3" × 3" (Square QR)',
        paperSize: 'Roll',
        paperWidthMm: 76.2,
        paperHeightMm: 76.2,
        cols: 1,
        rows: 1,
        labelWidthMm: 76.2,
        labelHeightMm: 76.2,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: '3 × 3 in square thermal label for QR codes / asset tags.'
    },
    {
        id: 'thermal-3x1',
        name: 'Thermal Roll — 3" × 1" (Shelf)',
        paperSize: 'Roll',
        paperWidthMm: 76.2,
        paperHeightMm: 25.4,
        cols: 1,
        rows: 1,
        labelWidthMm: 76.2,
        labelHeightMm: 25.4,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: '3 × 1 in thermal shelf / category label.'
    },
    {
        id: 'thermal-2x2',
        name: 'Thermal Roll — 2" × 2" (Square QR)',
        paperSize: 'Roll',
        paperWidthMm: 50.8,
        paperHeightMm: 50.8,
        cols: 1,
        rows: 1,
        labelWidthMm: 50.8,
        labelHeightMm: 50.8,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: '2 × 2 in square thermal label for compact QR codes.'
    },
    {
        id: 'thermal-2x1',
        name: 'Thermal Roll — 2" × 1" (1-Up Barcode)',
        paperSize: 'Roll',
        paperWidthMm: 50.8,
        paperHeightMm: 25.4,
        cols: 1,
        rows: 1,
        labelWidthMm: 50.8,
        labelHeightMm: 25.4,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: 'Compact thermal barcode stickers (2" × 1" continuous roll).'
    },
    {
        id: 'thermal-225x125',
        name: 'Thermal Roll — 2.25" × 1.25" (SKU)',
        paperSize: 'Roll',
        paperWidthMm: 57.15,
        paperHeightMm: 31.75,
        cols: 1,
        rows: 1,
        labelWidthMm: 57.15,
        labelHeightMm: 31.75,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: '2.25 × 1.25 in retail SKU / price tag thermal label.'
    },
    {
        id: 'thermal-1x1',
        name: 'Thermal Roll — 1" × 1" (Mini QR)',
        paperSize: 'Roll',
        paperWidthMm: 25.4,
        paperHeightMm: 25.4,
        cols: 1,
        rows: 1,
        labelWidthMm: 25.4,
        labelHeightMm: 25.4,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: '1 × 1 in thermal mini-label for small parts & asset QR.'
    },
    {
        id: 'thermal-4x65',
        name: 'Thermal Fanfold — 4" × 6.5" (Shipping)',
        paperSize: 'Roll',
        paperWidthMm: 101.6,
        paperHeightMm: 165.1,
        cols: 1,
        rows: 1,
        labelWidthMm: 101.6,
        labelHeightMm: 165.1,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: '4 × 6.5 in fanfold shipping label (Zebra Z-Perform 1000D style).'
    },

    // ── Continuous receipt rolls ───────────────────────────────────────────────
    {
        id: 'roll-80mm',
        name: 'Receipt Roll — 80 mm Continuous',
        paperSize: 'Roll',
        paperWidthMm: 80,
        paperHeightMm: 100,
        cols: 1,
        rows: 1,
        labelWidthMm: 80,
        labelHeightMm: 100,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: '80 mm continuous receipt/ticket roll (Epson, Star, thermal POS).'
    },
    {
        id: 'roll-58mm',
        name: 'Receipt Roll — 58 mm Continuous',
        paperSize: 'Roll',
        paperWidthMm: 58,
        paperHeightMm: 80,
        cols: 1,
        rows: 1,
        labelWidthMm: 58,
        labelHeightMm: 80,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: '58 mm continuous mobile receipt/ticket roll.'
    },
    {
        id: 'roll-110mm',
        name: 'Tag Roll — 110 mm Continuous (Brother QL-1110)',
        paperSize: 'Roll',
        paperWidthMm: 110,
        paperHeightMm: 110,
        cols: 1,
        rows: 1,
        labelWidthMm: 110,
        labelHeightMm: 110,
        marginTopMm: 0,
        marginBottomMm: 0,
        marginLeftMm: 0,
        marginRightMm: 0,
        gapXMm: 0,
        gapYMm: 0,
        description: '110 mm wide continuous label roll (Brother QL-1110NWB).'
    },

    // ── Custom ─────────────────────────────────────────────────────────────────
    {
        id: 'custom',
        name: 'Custom Sheet / Roll Grid',
        paperSize: 'Custom',
        paperWidthMm: 210,
        paperHeightMm: 297,
        cols: 3,
        rows: 7,
        labelWidthMm: 65,
        labelHeightMm: 38,
        marginTopMm: 10,
        marginBottomMm: 10,
        marginLeftMm: 7.5,
        marginRightMm: 7.5,
        gapXMm: 0,
        gapYMm: 0,
        description: 'Fully customizable sheet dimensions, grid layout, gaps, and margins.'
    }
];
